# Generated by Django 3.0 on 2019-12-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('slug', models.SlugField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=1000)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
