# Generated by Django 3.0 on 2019-12-15 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sirname', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('body', models.TextField(blank=True, db_index=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('blogger', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Blogger')),
            ],
        ),
    ]
