# Generated by Django 3.0 on 2019-12-14 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_blogger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blogger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blogger'),
        ),
    ]
